apiVersion: apps/v1
kind: Deployment    
metadata:
  name: frontend  
  labels:
    app: frontend 
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
      - name: frontend-app 
        image: gcr.io/bbk8-460817/frontend-deployment:1.3.2
        imagePullPolicy: IfNotPresent
        env:
        - name: VITE_REACT_APP_BACKEND_API_URL
          value: "http://34.57.73.26:80" 
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe: 
          httpGet:    
            path: /    
            port: 80  
            scheme: HTTP
          initialDelaySeconds: 10 
          periodSeconds: 5      
          failureThreshold: 3 
          successThreshold: 1
          timeoutSeconds: 1